// Display
export const MENU_TOGGLE = "MENU_TOGGLE";
export const SETTINGS_TOGGLE = "SETTINGS_TOGGLE";
// /Todo
export const SET_PRIORITY = "SET_PRIORITY";
export const GET_CURRENT_INPUT_VALUE = "GET_CURRENT_INPUT_VALUE";
export const CLEAR_FORM = "CLEAR_FORM";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const TOGGLE_STATUS = "TOGGLE_STATUS";
export const DELETE_SINGLE_TASK = "DELETE_SINGLE_TASK";
export const GET_TASKS = "GET_TASKS";
export const CLEAR_TODOS_AFTER_LOGOUT = "CLEAR_TODOS_AFTER_LOGOUT";
// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
